{
 "title": "sandbox",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "SHOW TAG VALUES FROM \"block\" WITH KEY = \"node\""
   }
  ]
 },
 "panels": [
  {
   "title": "Height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "node-$tag_node",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "block",
     "query": "SELECT \"height\" FROM \"block\" WHERE $timeFilter GROUP BY \"node\"",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node:tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "deviation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT stddev(\"height\") FROM \"block\" WHERE $timeFilter GROUP BY time(10m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Avg txs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Avg txs/s on 1-5",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"n\")/600 AS r FROM \"applied-txs\" WHERE node=3 and time > now() - 10m fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node =~ /$node/"
    }
   ]
  },
  {
   "title": "Avg txs/s on  6-10",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"n\")/600 AS r FROM \"applied-txs\" WHERE node=7 and time > now() - 10m fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node =~ /$node/"
    }
   ]
  },
  {
   "title": "Txs throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Txs throughput #$node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Positive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" >= 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Negative",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" < 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"r\"/10 FROM (SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(10m) fill(0))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Txs throughput #$node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Positive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" >= 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Negative",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" < 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"r\"/10 FROM (SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(10m) fill(0))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Txs throughput #$node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Positive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" >= 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Negative",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" < 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"r\"/10 FROM (SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(10m) fill(0))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Txs throughput #$node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Positive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" >= 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Negative",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" < 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"r\"/10 FROM (SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(10m) fill(0))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Txs throughput #$node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Positive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" >= 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Negative",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" < 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"r\"/10 FROM (SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(10m) fill(0))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Txs throughput #$node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Positive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" >= 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Negative",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" < 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"r\"/10 FROM (SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(10m) fill(0))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Txs throughput #$node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Positive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" >= 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Negative",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "txsInBlockchain",
       "query": "SELECT \"sum\" FROM (SELECT sum(\"n\") FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(1m) fill(0)) WHERE \"sum\" < 0",
       "select": [
        [
         { "params": [ "number" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"r\"/10 FROM (SELECT sum(\"n\") AS r FROM \"applied-txs\" WHERE $timeFilter AND node = $node GROUP BY time(10m) fill(0))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Blocks and micros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Blocks and micros",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_event $tag_source node",
     "groupBy": [
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "block",
     "query": "SELECT \"node\" FROM \"block\" WHERE $timeFilter GROUP BY \"event\", \"type\", \"source\"",
     "select": [
      [
       { "params": [ "node" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "1" },
      { "condition": "OR", "key": "node", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "node", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "node", "operator": "=", "value": "select tag value" }
     ],
     "target": "stats.timers.kamon-check.freezymac.histogram.some-histogram.*"
    }
   ]
  },
  {
   "title": "UtxPool size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "utx-pool-size",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "In $tag_type",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "block",
     "select": [
      [
       { "params": [ "txs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "Applied" }
     ]
    }
   ]
  },
  {
   "title": "Blocks and micros by node (can switch nodes)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_event $tag_source $node",
     "groupBy": [
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "block",
     "query": "SELECT \"node\" FROM \"block\" WHERE $timeFilter AND \"node\" = $node GROUP BY \"event\", \"type\", \"source\",  \"node\" ",
     "select": [
      [
       { "params": [ "node" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "1" },
      { "condition": "OR", "key": "node", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "node", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "node", "operator": "=", "value": "select tag value" }
     ],
     "target": "stats.timers.kamon-check.freezymac.histogram.some-histogram.*"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Total connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "0",
     "measurement": "connections",
     "query": "SELECT \"n\" FROM \"connections\" WHERE (\"node\" = 0) AND $timeFilter",
     "select": [
      [
       { "params": [ "n" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "1",
     "measurement": "connections",
     "query": "SELECT \"n\" FROM \"connections\" WHERE (\"node\" = 1) AND $timeFilter",
     "select": [
      [
       { "params": [ "n" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "2",
     "measurement": "connections",
     "query": "SELECT \"n\" FROM \"connections\" WHERE (\"node\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "n" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "3",
     "measurement": "connections",
     "query": "SELECT \"n\" FROM \"connections\" WHERE (\"node\" = 3) AND $timeFilter",
     "select": [
      [
       { "params": [ "n" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "4",
     "measurement": "connections",
     "query": "SELECT \"n\" FROM \"connections\" WHERE (\"node\" = 4) AND $timeFilter",
     "select": [
      [
       { "params": [ "n" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "5",
     "measurement": "connections",
     "query": "SELECT \"n\" FROM \"connections\" WHERE (\"node\" = 5) AND $timeFilter",
     "select": [
      [
       { "params": [ "n" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "-10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"n\" FROM \"connections\" WHERE (\"node\" = -10) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "UtxPool size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Utx Transaction Processing Time, milliseconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "utx-transaction-processing-time",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UtxPool put/ 10s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "utx-pool-put-if-new",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sync txs / 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "utx-sync-tx",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic  / 10s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $tag_type",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dir", "operator": "=", "value": "incoming" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "yolo-trafficWatcher",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Log kamon / 10s",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "yolo-discardingHandler",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "yolo-historyReplier",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "yolo-messageCodec",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "yolo-peerSynchronizer",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "yolo-trafficLogger",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "yolo-trafficWatcher",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "yolo-writeErrorHandler",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "waves-node@8" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "dir", "operator": "=", "value": "incoming" }
     ]
    }
   ]
  },
  {
   "title": "Blocks and micros, detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Detailed blocks and micros",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 123 },
     "targets": [
      {
       "measurement": "block-external",
       "query": "SELECT type, btype, \"from\", node AS \"to\", event, id, \"parent-id\", height, txs, bt, score FROM \"block\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks and micros, mined",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Detailed mined",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "measurement": "micro",
       "query": "SELECT type, btype, \"from\", node AS \"to\", id, \"parent-id\", height, txs, bt, score FROM \"block\" WHERE event='Mined' AND $timeFilter",
       "select": [
        [
         { "params": [ "node" ], "type": "field" }
        ],
        [
         { "params": [ "event" ], "type": "field" }
        ],
        [
         { "params": [ "id" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Forks analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forks monitoring",
     "type": "table-old",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 106 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT node AS \"to\", \"id\", \"height\" FROM \"block\" WHERE \"type\" = 'Block' AND (\"event\" = 'Applied' OR \"event\" = 'Mined') AND $timeFilter AND (node::tag = '3' OR node::tag = '1')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Total connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  { "title": "Rollbacks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Rollbacks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Rollback node",
     "measurement": "rollback",
     "select": [
      [
       { "params": [ "node" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Rollback depth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Rollback depth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rollback",
     "query": "SELECT \"depth\" FROM \"rollback\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "depth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "depth", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Transactions number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true
  },
  {
   "title": "Single block processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Single block processing 1m, ms",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "P95",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" }
       ],
       "measurement": "waves-node-timers",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         { "params": [ "1" ], "type": "top" }
        ]
       ],
       "tags": [
        { "key": "entity", "operator": "=", "value": "single-block-processing-time" }
       ]
      },
      {
       "alias": "Mean",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" }
       ],
       "measurement": "waves-node-timers",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity", "operator": "=", "value": "single-block-processing-time" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Propagation time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Propagation time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Broadcasted block",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "block",
     "query": "SELECT \"prop-time\" FROM \"block\" WHERE (\"event\" = 'Received') AND (\"type\" = 'Block') AND (\"source\" = 'Broadcast') AND $timeFilter",
     "select": [
      [
       { "params": [ "prop-time" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Extension block",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "block",
     "query": "SELECT \"prop-time\" FROM \"block\" WHERE (\"event\" = 'Received') AND (\"type\" = 'Block') AND (\"source\" = 'Ext') AND $timeFilter",
     "select": [
      [
       { "params": [ "prop-time" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Microblock",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "block",
     "query": "SELECT \"prop-time\" FROM \"block\" WHERE (\"event\" = 'Received') AND (\"type\" = 'Micro') AND $timeFilter",
     "select": [
      [
       { "params": [ "prop-time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Base target",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Base target of mined blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "1-5",
       "measurement": "block",
       "query": "SELECT \"bt\" FROM \"block\" WHERE \"event\" = 'Mined' AND \"type\" = 'Block' AND $timeFilter  AND \"node\" < 6",
       "select": [
        [
         { "params": [ "score" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "6-10",
       "measurement": "block",
       "query": "SELECT \"bt\" FROM \"block\" WHERE \"event\" = 'Mined' AND \"type\" = 'Block' AND $timeFilter  AND \"node\" > 5",
       "select": [
        [
         { "params": [ "score" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "table-old",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 132 },
     "targets": [
      {
       "measurement": "connections",
       "query": "SELECT \"node\", \"n\", \"incoming\",\"outgoing\" FROM \"connections\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "node" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Write (total)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "node.db.write",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DB Write",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_key",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "node.db.read",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" }
       ]
      }
     ]
    },
    {
     "title": "DB Read",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_key",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "node.db.read",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" }
       ]
      }
     ]
    },
    {
     "title": "DB Read (total)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "node.db.read",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "graph",
     "description": "rx - received\ntx - uploaded",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_hostname",
       "measurement": "waves-node-timers",
       "query": "SELECT \"upper\" FROM \"waves-node-timers\" WHERE (\"category\" = 'system-metric' AND \"entity\" = 'network' AND (\"metric\" = 'rx-bytes' OR \"metric\" = 'rx-bytes')) AND $timeFilter GROUP BY hostname",
       "select": [
        [
         { "params": [ "upper" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=", "value": "system-metric" },
        { "condition": "AND", "key": "entity", "operator": "=", "value": "network" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "rx-bytes" },
        { "condition": "OR", "key": "metric", "operator": "=", "value": "rx-bytes" }
       ]
      }
     ]
    }
   ]
  }
 ]
}